/**
	Generated by sails-inverse-model
	Date:Sun Aug 27 2017 04:56:47 GMT+0300 (Türkiye Standart Saati)
*/

module.exports = {
    attributes: {
        name: {
            type: 'string',
            required: true,
            unique: true
        },
        owner: {
            type: 'string',
        }
    }
};